name: caesar_qc
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.1.1
  - netCDF4=1.7.2
  - numpy=2.2.1
  - bokeh=3.6.2
  - holoviews=1.20.0
  - seaborn=0.13.2
  - scipy=1.15.1
  - hvplot=0.11.2
  - pandas=2.2.3
  - pytest=8.3.4
  - Pathlib=1.0.1
  - selenium=4.27.1
  - firefox=134.0
  - geckodriver=0.35.0
  - cartopy=0.24.0
  - xarray=2025.1.1
  - matplotlib=3.10.0
  - pip=24.3.1
  - metpy==1.6.3
  - nbconvert=7.16.5
  - panel=1.5.5
